name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: uname -r
      run: |
        uname -r
    
    
    - name: crun --version
      run: |
        crun --version


    - name: podman --version
      run: |
        podman --version

    - name: podman info
      run: |
        podman info
